### ISSUE TITLE
You have requested a non-existent parameter "dh_auditor.provider.doctrine.configuration".

### ISSUE THREAD

**Issue by vachigaggl** [DamienHarper/auditor#173]
I am on symfony 4.4 and amienharper/auditor-bundle 5.2.4.
However, I am getting not getting far:  The problem that appears immediately: 

> You have requested a non-existent parameter "dh_auditor.provider.doctrine.configuration".

with this Minimal config file:

```
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: ~
            table_suffix: '_audit'
```

Google returns 0 results for "dh_auditor.provider.doctrine.configuration".
