### ISSUE TITLE
DoctrineSubscriber throw deprecation when Driver is wrapped with another class

### ISSUE THREAD

**Issue by oleg-andreyev** [DamienHarper/auditor#184]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.7
| PHP version          | 8.1
| Database             | MySQL

#### Summary

I have both Auditor and Sentry packages.
Sentry also has a middleware that wraps connection with a special class.
Depending on priority of this middlewares `DoctrineSubscriber` may trigger a deprecation because $driver is not a `DHDriver`, but actually it's wrapped.

#### Current behavior

trigger deprecation when it's actually should not 

#### How to reproduce

Install both damienharper/auditor-bundle and sentry/sentry-symfony

#### Expected behavior

correct detection of `DHDriver`

**Comment by oleg-andreyev** [comment]
related also to

**Comment by DamienHarper** [comment]
@oleg-andreyev is this issue still relevant?

**Comment by oleg-andreyev** [comment]
@DamienHarper Relevant for 2.x

**Comment by DamienHarper** [comment]
@oleg-andreyev could you please share a way (code sample) so I can reproduce the issue?

**Comment by oleg-andreyev** [comment]
![image](https://github.com/DamienHarper/auditor/assets/1244112/78627d66-a22d-4ed0-b44b-ab1db3b5b304)

you'll need

```json
# composer.json

"sentry/sentry-symfony": "^4.6",
"damienharper/auditor-bundle": "^5.0",
```

```yaml
# sentry.yaml
sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        traces_sample_rate: 0.25
        # Set a sampling rate for profiling - this is relative to traces_sample_rate
        profiles_sample_rate: 1.0
        before_send: 'sentry.callback.before_send'
    register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface

```
