### ISSUE TITLE
No routes after updating to Symfony 6.4

### ISSUE THREAD

**Issue by lcpaf** [DamienHarper/auditor#202]
I upgraded my app to Symfony 6.4 (from 5.4), and out of a student I'm not able to register my audit routes.

```
#routes/dh_auditor.yaml
dh_auditor:
    resource: "@DHAuditorBundle/Controller/"
    type: auditor
```
I'm using attributes to declare my app routes, and I already tried to change the type to `attribute` as well, but no luck.

What is that I'm doing wrong?
